/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_Dealer;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author developer
 */
public class Car_Dealer extends javax.swing.JFrame {

    double[] i = new double[5];

    /**
     * Creates new form Car_Dealer
     */
    public Car_Dealer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCheckBox_Modified = new javax.swing.JCheckBox();
        jCheckBox_Sterio_system = new javax.swing.JCheckBox();
        jCheckBox_Customized = new javax.swing.JCheckBox();
        jCheckBox_Lether = new javax.swing.JCheckBox();
        jCheckBox_Global = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_distance_converter = new javax.swing.JComboBox<>();
        jTextField_distance_covered = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jTextField_Postal_code = new javax.swing.JTextField();
        jTextField_Telephone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField_time_Speed_distance = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_choose_car = new javax.swing.JComboBox<>();
        jComboBox_Trade_In = new javax.swing.JComboBox<>();
        jText_choose_car = new javax.swing.JTextField();
        jTextField_trade_in = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Tax_paid = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_sub_total = new javax.swing.JTextField();
        jTextField_Total = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox_Modified.setText("Modified");
        jPanel2.add(jCheckBox_Modified, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBox_Sterio_system.setText("Sterio System");
        jPanel2.add(jCheckBox_Sterio_system, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCheckBox_Customized.setText("Customized Dealing");
        jPanel2.add(jCheckBox_Customized, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jCheckBox_Lether.setText("Leather Interior");
        jPanel2.add(jCheckBox_Lether, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jCheckBox_Global.setText("Global Positioning System");
        jPanel2.add(jCheckBox_Global, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 520, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_distance_converter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Kilometre", "Miles", "Nautical Miles", " " }));
        jComboBox_distance_converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_distance_converterActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_distance_converter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, -1));
        jPanel3.add(jTextField_distance_covered, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, -1));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Result");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 40));

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 190, 260));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Name:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setText("Postal Code");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setText("Telephone");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel4.add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, -1));
        jPanel4.add(jTextField_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, -1));
        jPanel4.add(jTextField_Postal_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, -1));
        jPanel4.add(jTextField_Telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 230));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 310, 460));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Reset");
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jButton7.setText("Convert");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextField_time_Speed_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_time_Speed_distanceActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField_time_Speed_distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Distance", "Speed", "Time" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, -1));

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Result");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 200, 260));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Choose a Car");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel8.setText("Trade In ");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jComboBox_choose_car.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Pollo", "Pegiot", "BMW", "Land Cruiser", "Rav4" }));
        jComboBox_choose_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_choose_carActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox_choose_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));

        jComboBox_Trade_In.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00000", "50000", "100000", "150000", "200000", "3000000" }));
        jComboBox_Trade_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Trade_InActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox_Trade_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 180, -1));
        jPanel6.add(jText_choose_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 30));
        jPanel6.add(jTextField_trade_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 69, 180, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 490, 110));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Tax Paid");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel7.add(jTextField_Tax_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 450, 90));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Sub Total");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel11.setText("Total");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, -1));
        jPanel8.add(jTextField_sub_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 170, -1));
        jPanel8.add(jTextField_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 450, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 490, 80));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Car Dealer Systeml");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 390, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_distance_converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_distance_converterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_distance_converterActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed
    private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Exit the Car Dealing System", "Car Dealing System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jTextArea1.setText(null);
        jTextField_Address.setText(null);
        jTextField_Name.setText(null);
        jTextField_Postal_code.setText(null);
        jTextField_Tax_paid.setText(null);
        jTextField_Telephone.setText(null);
        jTextField_Total.setText(null);
        jTextField_distance_covered.setText(null);
        jTextField_sub_total.setText(null);
        jTextField_time_Speed_distance.setText(null);
        jTextField_trade_in.setText(null);
        jText_choose_car.setText(null);
        jComboBox_choose_car.setSelectedItem("------");
        jComboBox_Trade_In.setSelectedItem("00000");
        jComboBox_distance_converter.setSelectedItem("------");
        jComboBox4.setSelectedItem("----------");
        jCheckBox_Customized.setSelected(false);
        jCheckBox_Global.setSelected(false);
        jCheckBox_Lether.setSelected(false);
        jCheckBox_Modified.setSelected(false);
        jCheckBox_Sterio_system.setSelected(false);


    }//GEN-LAST:event_ResetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        double sterio = 100.45;
        double global = 209.34;
        double modified = 300.23;
        double tax = 12.9;
        double lether = 3000.32;
        double customize = 1020.23;
        double sum = 0;
        double AddAll;
        double iTax = 2.4;
        double Tax;
        double trade_in = Double.parseDouble(jTextField_trade_in.getText());
        double choose_car = Double.parseDouble(jText_choose_car.getText());

        jTextField_Total.setText(null);
        jTextField_sub_total.setText(null);

        //============================================================================pollo car ============================
        if (jCheckBox_Customized.isSelected() && jCheckBox_Global.isSelected() && jCheckBox_Lether.isSelected() && jCheckBox_Modified.isSelected() && jCheckBox_Sterio_system.isSelected()) {
            i[0] = sterio;
            i[1] = global;
            i[2] = modified;
            i[3] = lether;
            i[4] = customize;
            if (jComboBox_choose_car.getSelectedItem().equals("Pollo") && jComboBox_Trade_In.getSelectedItem().equals("00000")) {
                choose_car = choose_car - trade_in;
                AddAll = choose_car + i[0] + i[1] + i[2] + i[3] + i[4];
                Tax = (AddAll * iTax / 100);
                String sTax = String.format("%.2f", Tax);
                jTextField_Tax_paid.setText(sTax);
                String sub_total = String.format("%.2f", AddAll);
                jTextField_sub_total.setText(sub_total);
                String total = String.format("%.2f", (AddAll + Tax));
                jTextField_Total.setText(total);

            }
        } else {
            AddAll = choose_car - trade_in;
            String sub_total = String.format("%.2f", AddAll);
            jTextField_sub_total.setText(sub_total);
            Tax = (AddAll * iTax / 100);
            String sTax = String.format("%.2f", Tax);
            jTextField_Tax_paid.setText(sTax);
            String total = String.format("%.2f", AddAll + Tax);
            jTextField_Total.setText(total);
        }

        //============================================================================Pegiot car ============================
        if (jCheckBox_Customized.isSelected() && jCheckBox_Global.isSelected() && jCheckBox_Lether.isSelected() && jCheckBox_Modified.isSelected() && jCheckBox_Sterio_system.isSelected()) {
            i[0] = sterio;
            i[1] = global;
            i[2] = modified;
            i[3] = lether;
            i[4] = customize;
            if (jComboBox_choose_car.getSelectedItem().equals("Pegiot") && jComboBox_Trade_In.getSelectedItem().equals("50000")) {
                choose_car = choose_car - trade_in;
                AddAll = choose_car + i[0] + i[1] + i[2] + i[3] + i[4];
                Tax = (AddAll * iTax / 100);
                String sTax = String.format("%.2f", Tax);
                jTextField_Tax_paid.setText(sTax);
                String sub_total = String.format("%.2f", AddAll);
                jTextField_sub_total.setText(sub_total);
                String total = String.format("%.2f", (AddAll + Tax));
                jTextField_Total.setText(total);

            }
        } else {
            AddAll = choose_car - trade_in;
            String sub_total = String.format("%.2f", AddAll);
            jTextField_sub_total.setText(sub_total);
            Tax = (AddAll * iTax / 100);
            String sTax = String.format("%.2f", Tax);
            jTextField_Tax_paid.setText(sTax);
            String total = String.format("%.2f", AddAll + Tax);
            jTextField_Total.setText(total);
        }
//============================================================================BMW ============================

        if (jCheckBox_Customized.isSelected() && jCheckBox_Global.isSelected() && jCheckBox_Lether.isSelected() && jCheckBox_Modified.isSelected() && jCheckBox_Sterio_system.isSelected()) {
            i[0] = sterio;
            i[1] = global;
            i[2] = modified;
            i[3] = lether;
            i[4] = customize;
            if (jComboBox_choose_car.getSelectedItem().equals("BMW") && jComboBox_Trade_In.getSelectedItem().equals("100000")) {
                choose_car = choose_car - trade_in;
                AddAll = choose_car + i[0] + i[1] + i[2] + i[3] + i[4];
                Tax = (AddAll * iTax / 100);
                String sTax = String.format("%.2f", Tax);
                jTextField_Tax_paid.setText(sTax);
                String sub_total = String.format("%.2f", AddAll);
                jTextField_sub_total.setText(sub_total);
                String total = String.format("%.2f", (AddAll + Tax));
                jTextField_Total.setText(total);

            }
        } else {
            AddAll = choose_car - trade_in;
            String sub_total = String.format("%.2f", AddAll);
            jTextField_sub_total.setText(sub_total);
            Tax = (AddAll * iTax / 100);
            String sTax = String.format("%.2f", Tax);
            jTextField_Tax_paid.setText(sTax);
            String total = String.format("%.2f", AddAll + Tax);
            jTextField_Total.setText(total);
        }

//============================================================================Land Cruiser ============================
        if (jCheckBox_Customized.isSelected() && jCheckBox_Global.isSelected() && jCheckBox_Lether.isSelected() && jCheckBox_Modified.isSelected() && jCheckBox_Sterio_system.isSelected()) {
            i[0] = sterio;
            i[1] = global;
            i[2] = modified;
            i[3] = lether;
            i[4] = customize;
            if (jComboBox_choose_car.getSelectedItem().equals("Land Cruiser") && jComboBox_Trade_In.getSelectedItem().equals("150000")) {
                choose_car = choose_car - trade_in;
                AddAll = choose_car + i[0] + i[1] + i[2] + i[3] + i[4];
                Tax = (AddAll * iTax / 100);
                String sTax = String.format("%.2f", Tax);
                jTextField_Tax_paid.setText(sTax);
                String sub_total = String.format("%.2f", AddAll);
                jTextField_sub_total.setText(sub_total);
                String total = String.format("%.2f", (AddAll + Tax));
                jTextField_Total.setText(total);

            }
        } else {
            AddAll = choose_car - trade_in;
            String sub_total = String.format("%.2f", AddAll);
            jTextField_sub_total.setText(sub_total);
            Tax = (AddAll * iTax / 100);
            String sTax = String.format("%.2f", Tax);
            jTextField_Tax_paid.setText(sTax);
            String total = String.format("%.2f", AddAll + Tax);
            jTextField_Total.setText(total);
        }

//============================================================================Rav4 ============================
        if (jCheckBox_Customized.isSelected() && jCheckBox_Global.isSelected() && jCheckBox_Lether.isSelected() && jCheckBox_Modified.isSelected() && jCheckBox_Sterio_system.isSelected()) {
            i[0] = sterio;
            i[1] = global;
            i[2] = modified;
            i[3] = lether;
            i[4] = customize;
            if (jComboBox_choose_car.getSelectedItem().equals("Rav4") && jComboBox_Trade_In.getSelectedItem().equals("200000")) {
                choose_car = choose_car - trade_in;
                AddAll = choose_car + i[0] + i[1] + i[2] + i[3] + i[4];
                Tax = (AddAll * iTax / 100);
                String sTax = String.format("%.2f", Tax);
                jTextField_Tax_paid.setText(sTax);
                String sub_total = String.format("%.2f", AddAll);
                jTextField_sub_total.setText(sub_total);
                String total = String.format("%.2f", (AddAll + Tax));
                jTextField_Total.setText(total);

            }
        } else {
            AddAll = choose_car - trade_in;
            String sub_total = String.format("%.2f", AddAll);
            jTextField_sub_total.setText(sub_total);
            Tax = (AddAll * iTax / 100);
            String sTax = String.format("%.2f", Tax);
            jTextField_Tax_paid.setText(sTax);
            String total = String.format("%.2f", AddAll + Tax);
            jTextField_Total.setText(total);
        }

        //===============================================Receipts===============
        String name = jTextField_Name.getText();
        String address = jTextField_Address.getText();
        String postal_code = jTextField_Postal_code.getText();
        String sTax = jTextField_Tax_paid.getText();
        String phone = jTextField_Telephone.getText();
        String stotal = jTextField_Total.getText();
        String subtt = jTextField_sub_total.getText();
        String sold_car = jText_choose_car.getText();
        String strade = jTextField_trade_in.getText();

        jTextArea1.append("\tCar Dealer Systems\n\n"
                + "\nName:\t\t" + name
                + "\nAddress\t\t" + address
                + "\nPostal Code:\t\t" + postal_code
                + "\nCost\t\t" + sold_car
                + "\nTraded In\t\t" + strade
                + "\nTax\t\t" + sTax
                + "\nSub Total\t\t" + subtt
                + "\nTotal\t\t" + stotal
                + "\nTelephone\t\t" + phone
                + "\n\n\tThanks Buying From Us");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox_choose_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_choose_carActionPerformed
        double Pollo = 120000;
        double Pegiot = 300000;
        double BMW = 203000;
        double Land_Cruiser = 300000;
        double Rav4 = 400000;
        if (jComboBox_choose_car.getSelectedItem().equals("Pollo")) {
            String car = String.format("%.2f", Pollo);
            jText_choose_car.setText(car);
        }

        if (jComboBox_choose_car.getSelectedItem().equals("Pegiot")) {
            String car = String.format("%.2f", Pegiot);
            jText_choose_car.setText(car);
        }

        if (jComboBox_choose_car.getSelectedItem().equals("BMW")) {
            String car = String.format("%.2f", BMW);
            jText_choose_car.setText(car);
        }

        if (jComboBox_choose_car.getSelectedItem().equals("Land_Cruiser")) {
            String car = String.format("%.2f", Land_Cruiser);
            jText_choose_car.setText(car);
        }

        if (jComboBox_choose_car.getSelectedItem().equals("Rav4")) {
            String car = String.format("%.2f", Rav4);
            jText_choose_car.setText(car);
        }
        if (jComboBox_choose_car.getSelectedItem().equals("------")) {
            jText_choose_car.setText(null);
        }

    }//GEN-LAST:event_jComboBox_choose_carActionPerformed

    private void jComboBox_Trade_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Trade_InActionPerformed
        // TODO add your handling code here:
        double trade0 = 0;
        double trade1 = 500;
        double trade2 = 1000;
        double trade3 = 1500;
        double trade4 = 2000;
        double trade5 = 2500;
        if (jComboBox_Trade_In.getSelectedItem().equals("00000")) {
            String car1 = String.format("%.2f", trade0);
            jTextField_trade_in.setText(car1);
        }

        if (jComboBox_Trade_In.getSelectedItem().equals("50000")) {
            String car = String.format("%.2f", trade1);
            jTextField_trade_in.setText(car);
        }

        if (jComboBox_Trade_In.getSelectedItem().equals("100000")) {
            String car = String.format("%.2f", trade2);
            jTextField_trade_in.setText(car);
        }

        if (jComboBox_Trade_In.getSelectedItem().equals("150000")) {
            String car = String.format("%.2f", trade3);
            jTextField_trade_in.setText(car);
        }

        if (jComboBox_Trade_In.getSelectedItem().equals("200000")) {
            String car = String.format("%.2f", trade4);
            jTextField_trade_in.setText(car);
        }
        if (jComboBox_Trade_In.getSelectedItem().equals("300000")) {
            String car = String.format("%.2f", trade5);
            jTextField_trade_in.setText(car);
        }
    }//GEN-LAST:event_jComboBox_Trade_InActionPerformed

    private void jTextField_time_Speed_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_time_Speed_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_time_Speed_distanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double km = 0.62187;
        double mile;
        double nmile;
        //Kilometre

        if (jComboBox_distance_converter.getSelectedItem().equals("Kilometre")) {
            mile = Double.parseDouble(jTextField_distance_covered.getText());
            mile = mile * km;
            String skm = String.format("%.2f", mile);
            jLabel1.setText(skm);
        }

        if (jComboBox_distance_converter.getSelectedItem().equals("Miles")) {
            mile = Double.parseDouble(jTextField_distance_covered.getText());
            mile = mile / km;
            String skm = String.format("%.2f", mile);
            jLabel1.setText(skm);
        }

        if (jComboBox_distance_converter.getSelectedItem().equals("Nautical Miles")) {
            mile = Double.parseDouble(jTextField_distance_covered.getText());
            mile = mile / 1.15078;
            String skm = String.format("%.2f", mile);
            jLabel1.setText(skm);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox_distance_converter.setSelectedItem("------");
        jTextField_distance_covered.setText(null);
        jLabel1.setText("Result");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your han
        double dist;
        double speed;
        double time = 12;
        //Kilometre

        if (jComboBox4.getSelectedItem().equals("Distance")) {
            speed = Double.parseDouble(jTextField_time_Speed_distance.getText());
            dist = speed * time;
            String sdist = String.format("%.2f", dist);
            jLabel12.setText(sdist);

        }

        if (jComboBox4.getSelectedItem().equals("Speed")) {
            dist = Double.parseDouble(jTextField_time_Speed_distance.getText());
            speed = dist / time;
            String sdist = String.format("%.2f", speed);
            jLabel12.setText(sdist);

        }

        if (jComboBox4.getSelectedItem().equals("Time")) {
            speed = 80;
            dist = Double.parseDouble(jTextField_time_Speed_distance.getText());
            time = dist / speed;
            String sdist = String.format("%.2f", speed);
            jLabel12.setText(sdist);

        }


    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_Dealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox_Customized;
    private javax.swing.JCheckBox jCheckBox_Global;
    private javax.swing.JCheckBox jCheckBox_Lether;
    private javax.swing.JCheckBox jCheckBox_Modified;
    private javax.swing.JCheckBox jCheckBox_Sterio_system;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox_Trade_In;
    private javax.swing.JComboBox<String> jComboBox_choose_car;
    private javax.swing.JComboBox<String> jComboBox_distance_converter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Postal_code;
    private javax.swing.JTextField jTextField_Tax_paid;
    private javax.swing.JTextField jTextField_Telephone;
    private javax.swing.JTextField jTextField_Total;
    private javax.swing.JTextField jTextField_distance_covered;
    private javax.swing.JTextField jTextField_sub_total;
    private javax.swing.JTextField jTextField_time_Speed_distance;
    private javax.swing.JTextField jTextField_trade_in;
    private javax.swing.JTextField jText_choose_car;
    // End of variables declaration//GEN-END:variables
}
